spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_shop?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: lyh123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.shop.entity

server:
  port: 8080
